craft/food/cart/urls.py
from django.urls import path
from . import views

# app_name = 'cart'
#
# urlpatterns =[
#     path('', views.cart_detail, name='cart_detail'),
#     path('add/<int:product_id>/', views.cart_add, name='cart_add'),
#     path('remove/<int:product_id>/', views.cart_remove,  name='cart_remove'),
# ]

craft/food/craft/urls.py
from django.urls import path
from .views import (Home, Blog, CartView,
                    checkout,
                    Search, PostByTags, PostByCategory,
                    GetPost, MenuByCategory, SingleProduct,
                    add_to_card, remove_form_cart,
                    register, user_login, user_logout,
                    remove_single_item_from_cart, send_reserve_to_telegram,

                    )

# register, user_login, user_logout, send_reserve_to_telegram,

app_name = 'craft'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('menu/', MenuByCategory.as_view(), name='menu'),
    path('cart/', CartView.as_view(), name="cart"),
    path('checkout/', checkout, name="checkout"),
    path('blog/', Blog.as_view(), name='blog'),
    path('search/', Search.as_view(), name="search"),
    path('tag/<str:slug>/', PostByTags.as_view(), name="tag"),
    path('category/<str:slug>/', PostByCategory.as_view(), name="category"),
    path('single_post/<str:slug>/', GetPost.as_view(), name="post"),
    path('single_product/<str:slug>/', SingleProduct.as_view(), name="product"),
    path('add-to-cart/<str:slug>/', add_to_card, name='add-to-cart'),
    path('remove-from-cart/<str:slug>/', remove_form_cart, name='remove-from-cart'),
    path('remove-product-from-cart/<str:slug>/', remove_single_item_from_cart, name='remove-single-product-from-cart'),
    path('register', register, name='register'),
    path('user_login', user_login, name='login'),
    path('user_logout', user_logout, name='logout'),
    path('send_reserve_to_telegram/', send_reserve_to_telegram, name='send_reserve_to_telegram'),
    # path('menu/', product_list, name='product_list'),
    # path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    # # path('add-to-cart/', AddToCardView.as_view(), name='add_to_cart'),
    # path('menu/<str:category_slug>/', product_list, name='product_list_by_category'),
]
# path('create-comment/', create_comment, name='comment_create'),
# path('create-child-comment/', create_child_comment, name='comment_child_create'),
# path('post-comments/', index),

craft/food/food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('craft.urls', namespace='craft')),
    # path('accounts/', include('allauth.urls')),
    # path('ckeditor/', include('ckeditor_uploader.urls')),

]

# path('cart/', include('cart.urls', namespace='cart')),

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),
                   ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

craft/food/cart/models.py
from django.db import models

# Create your models here.

craft/food/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

craft/food/craft/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
# from captcha.fields import CaptchaField

# from .models import Comment
#
#
# class CommentForm(forms.ModelForm):
#
#     class Meta:
#         model = Comment
#         fields = ['text']


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={"class": "form-control"}))
    password1 = forms.CharField(label='Пороль', widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2 = forms.CharField(label='Подтверждения пороля', widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserloginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={"class": "form-control"}))


# CHOICE_TIME = [
#     '10:00',    '10:30',    '12:30',    '13:00',
#     '14:00',    '14:30',    '15:00',    '15:30',
#     '16:00',    '16:30',    '17:00',    '17:30',
#     '18:00',    '18:30',    '19:00',    '19:30',
#     '20:00',    '20:30',    '21:00',    '21:30',
#     '22:00',    '22:30',    '23:00',    '23:30',
#     '0:00',     '0:30',     '1:00',     '1:30',
#     '2:00',
# ]
#
# CHOICE_PERSON = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']


class ReserveForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-group'}), required=False)
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-group ml-md-4'}), required=False)
    date = forms.CharField(label='Номер телефона', widget=forms.SelectDateWidget(attrs={'class': 'form-group'}),
                           required=False)
    time = forms.ChoiceField(widget=forms.Select())
    # person = forms.ChoiceField(label='Колличество персон', widget=forms.Select(CHOICE_PERSON))
    massages = forms.CharField(label='Примечание', max_length=150, widget=forms.Textarea(attrs={'class': 'form-group'}),
                               required=False)


craft/food/cart/views.py
# from django.shortcuts import render, redirect, get_object_or_404
# from django.views.decorators.http import require_POST
# from craft.models import Product
# from .cart import Cart
# from .forms import CartAddProductForm


# @require_POST
# def cart_add(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     form = CartAddProductForm(request.POST)
#     if form.is_valid():
#         cd = form.cleaned_data
#         cart.add_product(product=product,
#                          quantity=cd['quantity'],
#                          update_quantity=cd['update'])
#     return redirect('cart:cart_detail')


# def cart_remove(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     cart.remove(product)
#     return redirect('cart:cart_detail')


# def cart_detail(request):
#     cart = Cart(request)
#     # for item in cart:
#     #     item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
#     #                                                       'update': True})
#     return render(request, 'craft/cart.html', {'cart': cart})

craft/food/craft/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F
from django.shortcuts import render, get_object_or_404, redirect


from django.db import transaction
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic import View
from .forms import UserRegisterForm, UserloginForm, ReserveForm
from django.contrib.auth import login, logout
from cart.forms import CartAddProductForm
# from .utils import create_comments_tree

from .models import *
# from craft.telegram.bot_utils import send_massages
# from .forms import CommentForm


class Home(ListView):
    model = Post
    template_name = 'craft/index.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'CRAFT'
        return context


class Blog(ListView):
    model = Post
    template_name = 'craft/blog.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.filter(published_at=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'BLOG'
        return context


class Search(ListView):
    template_name = 'craft/search.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        return Post.objects.filter(title__icontains=self.request.GET.get('s'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['s'] = f's={self.request.GET.get("s")}&'
        return context


class PostByCategory(ListView):
    model = Post
    template_name = "craft/post_category.html"
    context_object_name = 'cats'
    paginate_by = 3
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Посты по категории'
        return context


class PostByTags(ListView):
    model = Post
    template_name = 'craft/post_tags.html'
    context_object_name = 'tags'
    paginate_by = 3

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Записи по тегам: ' + str(Tag.objects.get(slug=self.kwargs['slug']))
        return context


class GetPost(DetailView):
    # single post
    model = Post
    template_name = 'craft/single.html'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object.views = F('views') + 1
        self.object.save()
        self.object.refresh_from_db()
        return context


class MenuByCategory(ListView):
    model = MenuCategory
    template_name = 'craft/menu.html'
    context_object_name = 'menus'

    def get_queryset(self):
        return Product.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Menu'
        context['categories'] = MenuCategory.objects.all()
        return context


class SingleProduct(DetailView):
    model = Product
    template_name = 'craft/single_product.html'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Product.objects.get(slug=self.kwargs['slug'])
        return context
# context_object_name = 'cart_list'


class CartView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'craft/cart.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "У вас нет покупок")
            return redirect('craft:home')


@login_required
def add_to_card(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_item, created = CartProduct.objects.get_or_create(product=product,
                                                            user=request.user,
                                                            ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # проверяем есть ли в корзине продукт из заказа
        if order.products.filter(product__slug=product.slug).exists():
            order_item.quality += 1
            order_item.save()
            messages.info(request, "Колличество было изменнено!")
            return redirect("craft:cart")
        else:
            messages.info(request, "Добавлен в вашу корзину!")
            order.products.add(order_item)
            return redirect("craft:cart")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.products.add(order_item)
        messages.info(request, "Добавлен в вашу корзину!")
        return redirect("craft:menu")


@login_required
def remove_form_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # проверяем есть ли в корзине продукт из заказа
        if order.products.filter(product__slug=product.slug).exists():
            order_item = CartProduct.objects.filter(product=product,
                                                    user=request.user,
                                                    ordered=False)[0]
            order.products.remove(order_item)
            messages.info(request, "Удален с вашей корзины!")
            return redirect("craft:cart")
        else:
            messages.info(request, "Итема нет в вашей корзине!")
            return redirect("craft:cart")
    else:
        messages.info(request, "У вас нет активных корзин!")
        return redirect("craft:menu")


@login_required
def remove_single_item_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # проверяем есть ли в корзине продукт из заказа
        if order.products.filter(product__slug=product.slug).exists():
            order_item = CartProduct.objects.filter(product=product,
                                                    user=request.user,
                                                    ordered=False)[0]
            if order_item.quality > 1:
                order_item.quality -= 1
                order_item.save()
            else:
                order.products.remove(order_item)
            messages.info(request, "Колличество было изменено!")
            return redirect("craft:cart")
        else:
            messages.info(request, "Итема нет в вашей корзине!")
            return redirect("craft:cart")
    else:
        messages.info(request, "У вас нет активных корзин!")
        return redirect("craft:menu")


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Вы успешно зарегистрировались.")
            return redirect('craft:home')
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = UserRegisterForm()
    return render(request, 'craft/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = UserloginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('craft:home')
    else:
        form = UserloginForm()
    return render(request, 'craft/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('craft:login')


def checkout(request):
    return render(request, "craft/checkout.html")


def send_reserve_to_telegram(request):
    if request.method == 'POST':
        form = ReserveForm(request.POST)
        text = f'Имя: {form.data["username"]}' \
               f'\nНомер телефона: {form.data["phone_number"]}' \
               f'\nДата: {form.data["date"]}' \
               f'\nВремя резерва: {form.data["time"]}' \
               f'\nПримечание: {form.data["massages"]}'
        # send_massages(text)
        # if send_massages:
        #     messages.info(request, 'Запрос о резерве отправлен.')
        # else:
        #     messages.error(request, 'Ошибка отправки.')
        # return redirect('craft:home')
    else:
        form = ReserveForm()
    return render(request, 'craft/index.html', {'form': form})
#

# class AddToCardView(View):
#
#     def get_queryset(self):

craft/food/craft/templates/craft/blog.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ title }} :: {{ block.super}}
{% endblock %}

{% block content %}
<!--слайдер-->
<section class="home-slider owl-carousel">

    <div class="slider-item" style="background-image: url(images/bg_3.jpg);" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row slider-text justify-content-center align-items-center">
                <div class="col-md-7 col-sm-12 text-center ftco-animate">
                    <h1 class="mb-3 mt-5 bread">Blog</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'craft:home' %}">Home</a></span> <span>Blog</span></p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row d-flex">
            {% for post in posts %}
                <div class="col-md-4 d-flex ftco-animate">
                    <div class="blog-entry align-self-stretch">
                        <a href="{{ post.get_absolute_url }}" class="block-20" style="background-image: url({{ post.photo.url }});">
                        </a>
                        <div class="text py-4 d-block">
                            <div class="meta">
                                <div>Дата: {{ post.created_at|date:"Y-m-d"}}</a></div>
                                <div></a></div>
                                <div>Просмотры: {{ post.views }}</a></div>
                            </div>
                            <h3 class="heading mt-2"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                            <p>{{ post.content|safe|truncatewords_html:50 }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    {% if page_obj.has_other_pages %}
                    <ul>
                        {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                        {% endif %}

                        {% for p in page_obj.paginator.page_range %}
                            {% if page_obj.number == p %}
                            <li><a href="?page={{ p }}">{{p}}</a></li>
                            {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                            <li><a href="?page={{ p }}">{{p}}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

craft/food/craft/templates/craft/last_post_tpl.html
<div class="sidebar-box ftco-animate">
    <h3>Blog</h3>
    {% for post in posts %}
    <div class="block-21 mb-4 d-flex">
        <a class="blog-img mr-4" style="background-image: url({{ post.photo.url}});"></a>
        <div class="text">
            <h3 class="heading"><a href="{{ post.get_absolute_url }}">{{ post.content|safe|truncatewords_html:10 }}</a></h3>
            <div class="meta">
                <div><span class="icon-calendar"></span>{{ post.created_at|date:"Y-m-d" }}</a></div>
<!--                <div><span class="icon-person"></span></a></div>-->
            </div>
        </div>
    </div>
    {% endfor %}
</div>

craft/food/craft/templates/craft/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'craft:product_list' %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

craft/food/craft/templates/craft/login.html
{% extends 'craft/base.html' %}
{% load slider_posts %}
<!--{% load crispy_forms_tags %}-->

{% block title %}
ПегиДудочник :: {{ block.super }}
{% endblock  %}



{% block content %}
<!--    {% get_slider_post %}-->
    <div class="col-md-12 text-center ">
    <h3>Авторизация</h3>
    <form class="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-dark">Login</button>
        <p>
            Если вы еще не создали аккаунт тогда <a href="{% url 'craft:register' %}" class="type-text ">зарегистрируйтесь</a>
        </p>

    </form>
    </div>
{% endblock  %}

craft/food/craft/templates/craft/post.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!--слайдер-->
<section class="home-slider owl-carousel">

    <div class="slider-item" style="background-image: url(images/bg_3.jpg);" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row slider-text justify-content-center align-items-center">

                <div class="col-md-7 col-sm-12 text-center ftco-animate">
                    <h1 class="mb-3 mt-5 bread">Blog</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Blog</span></p>
                </div>

            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row d-flex">
            {% for post in posts %}
            <div class="col-md-4 d-flex ftco-animate">
                <div class="blog-entry align-self-stretch">
                    <a href="blog-single.html" class="block-20" style="background-image: url({{ post.photo.url }});">
                    </a>
                    <div class="text py-4 d-block">
                        <div class="meta">
                            <div><a href="#">{{post.created_at|date:"Y-m-d"}}</a></div>
                            <div><a href="#">{{ post.author }}</a></div>
                            <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                        </div>
                        <h3 class="heading mt-2"><a href="#">{{ post.title }}</a></h3>
                        <p>{{ post.content|safe }}</p>
                    </div>
                </div>
            </div>
            {% endblock %}

        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        <li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

craft/food/craft/templates/craft/register.html
{% extends 'base.html' %}
{% load slider_posts %}
{% load crispy_forms_tags %}

{% block title %}
ПегиДудочник :: {{ block.super }}
{% endblock  %}



{% block content %}
	{% get_slider_post %}
    <div class="col-md-12 text-center">
        <h1>Регистрация</h1>
        <form  method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-dark">Зарегистрироваться</button>

        </form>
    </div>
{% endblock %}

craft/food/craft/templates/craft/single.html
{% extends 'base.html' %}
{% load static %}
{% load sidebar_box %}

{% load crispy_forms_tags %}

{% block title %}
{{ post.title }} :: {{ block.super}}
{% endblock %}


{% block content %}
<!--слайдер-->
<section class="home-slider owl-carousel">

    <div class="slider-item" style="background-image: url({{ post.photo.url }});" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row slider-text justify-content-center align-items-center">

                <div class="col-md-7 col-sm-12 text-center ftco-animate">
                    <h1 class="mb-3 mt-5 bread">{{ post.title }}</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'craft:home' %}">Home</a></span><span
                            class="mr-2"><a
                            href="{% url 'craft:blog' %}">Blog</a></span><span>Blog Single</span></p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">
            <h2 class="mb-3"><i>{{ post.title }}</i></h2>
              <div>
                  Категории:<a href="{{ post.category.get_absolute_url }}"> {{ post.category }}</a>
                  <br>
                  <span>Просмотры:  {{ post.views }}</span>
              </div>

                <p>{{ post.content|safe }}</p>
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tags in post.tags.all %}
                        <a href="{{ tags.get_absolute_url }}" class="tag-cloud-link">{{ tags.title }}</a>
                        {% endfor %}
                    </div>
                </div>

            <div class="about-author d-flex">
              <div class="bio align-self-md-center mr-5">
                <img src="{% static 'images/person_4.jpg' %}" alt="Image placeholder" class="img-fluid mb-4">
              </div>
              <div class="desc align-self-md-center">
                <h3>Lance Smith</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Ducimus itaque, autem necessitatibus voluptate
                    quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique,
                    inventore eos fugit cupiditate numquam!
                </p>
              </div>
            </div>
          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar">
            <div class="sidebar-box">
              <form action="{% url 'craft:search' %}" method="get">
                <div class="form-group">
                	<input type="text" name="s" placeholder="Поиск...">
	                  <input type="submit" value="Поиск...">
                  </div>
                  <input type="text" class="form-control" placeholder="Search...">
              </form>
            </div>
            {% get_post_cat %}

            {% get_last_post %}

            {% get_tag_cloud %}

            <div class="sidebar-box ftco-animate">
              <h3>Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque,
                  autem necessitatibus voluptate quod mollitia delectus aut,
                  sunt placeat nam vero culpa sapiente consectetur similique,
                  inventore eos fugit cupiditate numquam!
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

<!-- .section -->
<!--<script>-->
<!--      $(document).ready(function(){-->
<!--        $(".reply").on('click', function(){-->
<!--          var commentId = $(this).attr('data-id')-->
<!--          $("#form-"+commentId).fadeToggle();-->
<!--        })-->
<!--        $(".submit-reply").on("click", function(e){-->
<!--          e.preventDefault()-->
<!--          var parentId = $(this).attr("data-submit-reply")-->
<!--          var id = $(this).attr("data-id")-->
<!--          var text = $("#form-"+id).find("textarea[name='comment-text']").val();-->
<!--          function getCookie(name) {-->
<!--          let cookieValue = null;-->
<!--          if (document.cookie && document.cookie !== '') {-->
<!--              const cookies = document.cookie.split(';');-->
<!--              for (let i = 0; i < cookies.length; i++) {-->
<!--                  const cookie = cookies[i].trim();-->
<!--                  // Does this cookie string begin with the name we want?-->
<!--                  if (cookie.substring(0, name.length + 1) === (name + '=')) {-->
<!--                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));-->
<!--                      break;-->
<!--                  }-->
<!--              }-->
<!--          }-->
<!--          return cookieValue;-->
<!--        }-->
<!--        const csrftoken = getCookie('csrftoken');-->
<!--        data = {-->
<!--          user: "{{ request.user.username }}",-->
<!--          parentId: parentId,-->
<!--          text: text,-->
<!--          id: id,-->
<!--          csrfmiddlewaretoken: csrftoken-->
<!--        }-->
<!--        $.ajax({-->
<!--          method: "Post",-->
<!--          data: data,-->
<!--          url: "{% url 'craft:comment_child_create' %}",-->
<!--          success: function(data){-->
<!--            window.location.replace("/test.html")-->

<!--          }-->
<!--        })-->
<!--      })-->
<!--    })-->
<!--</script>-->