craft/food/cart/urls.py
from django.urls import path
from . import views

# app_name = 'cart'
#
# urlpatterns =[
#     path('', views.cart_detail, name='cart_detail'),
#     path('add/<int:product_id>/', views.cart_add, name='cart_add'),
#     path('remove/<int:product_id>/', views.cart_remove,  name='cart_remove'),
# ]

craft/food/craft/urls.py
from django.urls import path
from .views import (Home, Blog, CartView,
                    checkout,
                    Search, PostByTags, PostByCategory,
                    GetPost, MenuByCategory, SingleProduct,
                    add_to_card, remove_form_cart,
                    register, user_login, user_logout,
                    remove_single_item_from_cart, send_reserve_to_telegram,

                    )

# register, user_login, user_logout, send_reserve_to_telegram,

app_name = 'craft'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('menu/', MenuByCategory.as_view(), name='menu'),
    path('cart/', CartView.as_view(), name="cart"),
    path('checkout/', checkout, name="checkout"),
    path('blog/', Blog.as_view(), name='blog'),
    path('search/', Search.as_view(), name="search"),
    path('tag/<str:slug>/', PostByTags.as_view(), name="tag"),
    path('category/<str:slug>/', PostByCategory.as_view(), name="category"),
    path('single_post/<str:slug>/', GetPost.as_view(), name="post"),
    path('single_product/<str:slug>/', SingleProduct.as_view(), name="product"),
    path('add-to-cart/<str:slug>/', add_to_card, name='add-to-cart'),
    path('remove-from-cart/<str:slug>/', remove_form_cart, name='remove-from-cart'),
    path('remove-product-from-cart/<str:slug>/', remove_single_item_from_cart, name='remove-single-product-from-cart'),
    path('register', register, name='register'),
    path('user_login', user_login, name='login'),
    path('user_logout', user_logout, name='logout'),
    path('send_reserve_to_telegram/', send_reserve_to_telegram, name='send_reserve_to_telegram'),
    # path('menu/', product_list, name='product_list'),
    # path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    # # path('add-to-cart/', AddToCardView.as_view(), name='add_to_cart'),
    # path('menu/<str:category_slug>/', product_list, name='product_list_by_category'),
]
# path('create-comment/', create_comment, name='comment_create'),
# path('create-child-comment/', create_child_comment, name='comment_child_create'),
# path('post-comments/', index),

craft/food/food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('craft.urls', namespace='craft')),
    # path('accounts/', include('allauth.urls')),
    # path('ckeditor/', include('ckeditor_uploader.urls')),

]

# path('cart/', include('cart.urls', namespace='cart')),

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),
                   ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

craft/food/templates/inc/_footer.html
{% load static %}
<footer class="ftco-footer ftco-section img">
    <div class="overlay"></div>
    <div class="container">
        <div class="row mb-5">
            <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">About Us</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia
                        and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Recent Blog</h2>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'images/image_2.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> Sept 15, 2018</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Cooked</a></li>
                        <li><a href="#" class="py-2 d-block">Deliver</a></li>
                        <li><a href="#" class="py-2 d-block">Quality Foods</a></li>
                        <li><a href="#" class="py-2 d-block">Mixed</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<!--        <div class="row">-->
<!--            <div class="col-md-12 text-center">-->

<!--&lt;!&ndash;                <p>&lt;!&ndash; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. &ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>&ndash;&gt;-->
<!--&lt;!&ndash;                    All rights reserved | This template is made with&ndash;&gt;-->
<!--&lt;!&ndash;                    <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>&ndash;&gt;-->
<!--&lt;!&ndash;                    &lt;!&ndash; Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. &ndash;&gt;</p>&ndash;&gt;-->
<!--            </div>-->
<!--        </div>-->
    </div>
</footer>

craft/food/templates/inc/_header.html
{% load cart_template_tag %}

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'craft:home' %}">Craft<small>launch room</small></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active "><a href="{% url 'craft:home' %}"  class="nav-link">Home</a>

                </li>
                <li class="nav-item"><a href="{% url 'craft:menu' %}" class="nav-link">Menu</a></li>
                <li class="nav-item"><a href="{% url 'craft:blog' %}" class="nav-link">Blog</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Services</a></li>
                <li class="nav-item"><a href="#" class="nav-link">About</a></li>

                {% if request.user.is_authenticated %}
                <li class="nav-item person "><a href="{% url 'account_logout' %}" class="nav-link font-italic"><span class="oi oi-person"></span> {{ user.username}}</a></li>
                <li class="nav-item cart"><a href="{% url 'craft:cart' %}" class="nav-link"><span class="icon icon-shopping_cart"></span>
                    <span class="bag d-flex justify-content-center align-items-center"><small>{{ request.user|cart_item_count }}</small></span></a>
                </li>
                {% else %}
                <li class="nav-item"><a href="#" class="nav-link oi oi-account-login">Вход</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>